apiVersion: v1
kind: Service
metadata:
  name: yorkie-service
  labels:
    app: yorkie-server
spec:
  clusterIP: None
  selector:
    app: yorkie-server
  ports:
    - name: sdk-port
      port: 11101
      targetPort: 11101
    - name: profiling-port
      port: 11102
      targetPort: 11102
    - name: admin-port
      port: 11103
      targetPort: 11103
