apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker/yorkie-custom-docker/docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: envoy
  name: envoy
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9901"
      port: 9901
      targetPort: 9901
  selector:
    io.kompose.service: envoy
status:
  loadBalancer: {}
