apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: yorkie
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
      name: mongo-port
      appProtocol: tcp