apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: yorkie-gateway
spec:
  # use istio default controller
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
