apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: yorkie
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: yorkie
    app.kubernetes.io/managed-by: kubernetes
spec:
  type: ClusterIP
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    appProtocol: tcp
# TODO(hackerwins): Find an image for ARM64
#  - name: mongodb-exporter
#    port: 9216
#    targetPort: 9216
  selector:
    app.kubernetes.io/instance: mongodb
