{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: yorkie
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: yorkie
    app.kubernetes.io/managed-by: kubernetes
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mongodb
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
        - name: mongodb
          image: mongo:4.4.1
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
          # resources will be configured in later updates
          # (need to load test to configure resource capacity)
          resources: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
{{- end }}
