apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.yorkie.name }}-gateway
  namespace: {{ .Values.yorkie.namespace }}
spec:
  # use istio default controller
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
