apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: yorkie
  labels:
    app: etcd
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
    - name: client-port
      port: 2379
      targetPort: 2379
    - name: peer-port
      port: 2380
      targetPort: 2380
