apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: yorkie
  labels:
    app: mongo
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - name: mongo-port
      port: 27017
      targetPort: 27017
